Repository BCDA-APS/BITS, pull requests merged in 2025-03, with the labels that each got.

#40 Factory methods for motors and ophyd simulators
  docs/source/api/devices.rst
  src/instrument/configs/devices.yml
  src/instrument/devices/__init__.py
  src/instrument/devices/factories.py
  src/instrument/plans/sim_plans.py
  src/instrument/tests/test_device_factories.py
  src/instrument/utils/make_devices_yaml.py
Labels: enhancement

#51 GHA for repo initialization.
  .github/workflows/init_repo.sh
  .github/workflows/init_repo.yml
Labels: documentation, enhancement

#52 CI #51 fix copy/paste typo
  .github/workflows/init_repo.yml
Labels: bug

#38 how to sync a repo when template is updated
  .github/workflows/template-sync.yml
  README.md
  docs/source/guides/index.rst
  docs/source/guides/template_sync.rst
  docs/source/index.rst
Labels: documentation

#47 MNT: BITS structure cleanup
  .github/workflows/template-sync.yml
  README.md
  docs/source/guides/index.rst
  docs/source/guides/template_sync.rst
  pyproject.toml
  src/instrument/callbacks/nexus_data_file_writer.py
  src/instrument/callbacks/spec_data_file_writer.py
  src/instrument/configs/devices.yml
  src/instrument/configs/iconfig.yml
  src/instrument/startup.py
  src/instrument/tests/test_device_factories.py
  src/instrument/tests/test_general.py
  src/instrument/utils/sim_creator.py
Labels: bug, enhancement

#58 Demo instrument separation for Sync template
  .github/workflows/code.yml
  .github/workflows/init_repo.sh
  .github/workflows/init_repo.yml
  .github/workflows/template_sync.yml
  .templatesyncignore
  docs/source/api/configs.rst
  docs/source/conf.py
  docs/source/demo.ipynb
  pyproject.toml
  src/bits/__init__.py
  src/bits/callbacks/__init__.py
  src/bits/callbacks/nexus_data_file_writer.py
  src/bits/callbacks/spec_data_file_writer.py
  src/bits/core/__init__.py
  src/bits/core/best_effort_init.py
  src/bits/core/catalog_init.py
  src/bits/core/run_engine_init.py
  src/bits/demo_instrument/README.md
  src/bits/demo_instrument/__init__.py
  src/bits/demo_instrument/configs/__init__.py
  src/bits/demo_instrument/configs/devices.yml
  src/bits/demo_instrument/configs/devices_aps_only.yml
  src/bits/demo_instrument/configs/iconfig.yml
  src/bits/demo_instrument/configs/logging.yml
  src/bits/demo_instrument/devices/__init__.py
  src/bits/demo_instrument/plans/__init__.py
  src/bits/demo_instrument/plans/dm_plans.py
  src/bits/demo_instrument/plans/sim_plans.py
  src/bits/demo_instrument/startup.py
  src/bits/tests/__init__.py
  src/bits/tests/conftest.py
  src/bits/tests/test_device_factories.py
  src/bits/tests/test_general.py
  src/bits/tests/test_stored_dict.py
  src/bits/utils/__init__.py
  src/bits/utils/aps_functions.py
  src/bits/utils/config_loaders.py
  src/bits/utils/controls_setup.py
  src/bits/utils/create_new_instrument.py
  src/bits/utils/helper_functions.py
  src/bits/utils/logging_setup.py
  src/bits/utils/make_devices_yaml.py
  src/bits/utils/metadata.py
  src/bits/utils/sim_creator.py
  src/bits/utils/stored_dict.py
Labels: documentation, enhancement

#69 DOC merge a branch will push to PyPI?
  README.md
Labels: documentation

#59 Init/Sync/Create Instruments
  .github/workflows/init_repo.sh
  README.md
  docs/resources/create-repository-name.webp
  docs/resources/create-repository-owner.webp
  docs/resources/use-this-template-button.webp
  pyproject.toml
  src/bits/__init__.py
  src/bits/core/__init__.py
  src/bits/core/run_engine_init.py
  src/bits/demo_instrument/callbacks/__init__.py
  src/bits/demo_instrument/callbacks/nexus_data_file_writer.py
  src/bits/demo_instrument/callbacks/spec_data_file_writer.py
  src/bits/demo_instrument/configs/iconfig.yml
  src/bits/demo_instrument/startup.py
  src/bits/utils/aps_functions.py
  src/bits/utils/config_loaders.py
  src/bits/utils/context_aware.py
  src/bits/utils/controls_setup.py
  src/bits/utils/create_new_instrument.py
  src/bits/utils/helper_functions.py
  src/bits/utils/make_devices_yaml.py
Labels: documentation, enhancement, task

#73 New explicit instructions for new instrument
  pyproject.toml
  src/apsbits/core/best_effort_init.py
  src/apsbits/core/catalog_init.py
  src/apsbits/core/run_engine_init.py
  src/apsbits/demo_instrument/__init__.py
  src/apsbits/demo_instrument/callbacks/nexus_data_file_writer.py
  src/apsbits/demo_instrument/callbacks/spec_data_file_writer.py
  src/apsbits/demo_instrument/configs/iconfig.yml
  src/apsbits/demo_instrument/startup.py
  src/apsbits/tests/conftest.py
  src/apsbits/tests/test_config.py
  src/apsbits/tests/test_general.py
  src/apsbits/utils/config_loaders.py
  src/apsbits/utils/context_aware.py
  src/apsbits/utils/controls_setup.py
  src/apsbits/utils/create_new_instrument.py
  src/apsbits/utils/helper_functions.py
  src/apsbits/utils/logging_setup.py
  src/apsbits/utils/make_devices.py
  src/apsbits/utils/metadata.py
  src/apsbits/utils/sim_creator.py
  src/apsbits/utils/stored_dict.py
Labels: bug, documentation, enhancement, dependencies

#95 Add a release history file
  HISTORY.rst
  docs/source/history.rst
  docs/source/index.rst
Labels: documentation

#97 Documentation overhaul1
  docs/source/api/callbacks.rst
  docs/source/api/configs.rst
  docs/source/api/core.rst
  docs/source/api/demo_instrument.rst
  docs/source/api/demo_qserver.rst
  docs/source/api/devices.rst
  docs/source/api/generated/apsbits.core.best_effort_init.rst
  docs/source/api/generated/apsbits.core.catalog_init.rst
  docs/source/api/generated/apsbits.core.run_engine_init.rst
  docs/source/api/generated/apsbits.demo_instrument.callbacks.nexus_data_file_writer.rst
  docs/source/api/generated/apsbits.demo_instrument.callbacks.rst
  docs/source/api/generated/apsbits.demo_instrument.callbacks.spec_data_file_writer.rst
  docs/source/api/generated/apsbits.demo_instrument.configs.rst
  docs/source/api/generated/apsbits.demo_instrument.devices.rst
  docs/source/api/generated/apsbits.demo_instrument.plans.dm_plans.rst
  docs/source/api/generated/apsbits.demo_instrument.plans.rst
  docs/source/api/generated/apsbits.demo_instrument.plans.sim_plans.rst
  docs/source/api/generated/apsbits.demo_instrument.rst
  docs/source/api/generated/apsbits.demo_instrument.startup.rst
  docs/source/api/generated/apsbits.demo_qserver.rst
  docs/source/api/generated/apsbits.utils.aps_functions.rst
  docs/source/api/generated/apsbits.utils.config_loaders.rst
  docs/source/api/generated/apsbits.utils.controls_setup.rst
  docs/source/api/generated/apsbits.utils.helper_functions.rst
  docs/source/api/generated/apsbits.utils.logging_setup.rst
  docs/source/api/generated/apsbits.utils.metadata.rst
  docs/source/api/generated/apsbits.utils.stored_dict.rst
  docs/source/api/index.rst
  docs/source/api/plans.rst
  docs/source/api/startup.rst
  docs/source/api/utils.rst
  docs/source/console.rst
  docs/source/guides/index.rst
  docs/source/guides/qserver_service.rst
  docs/source/guides/template_creation.rst
  docs/source/guides/template_sync.rst
  docs/source/index.rst
  docs/source/license.rst
  docs/source/notebook.rst
  docs/source/qserver.rst
  docs/source/resources/create-repo-from-template.webp
  docs/source/resources/create-repository-owner.webp
  docs/source/resources/use-this-template-button.webp
  docs/source/script.rst
  docs/template_creation.md
  src/apsbits/demo_instrument/configs/devices.yml
Labels: documentation, enhancement
